# Generated by Django 5.2.9 on 2025-12-23 04:35

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Marketing_Research', '0031_alter_pmrresearchlist_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '公司列表',
                'db_table': 'marketing_research_v2"."Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportUserInfo',
            fields=[
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'db_table': 'django_admin_v2"."auth_user',
                'managed': False,
                'proxy': True,
            },
            bases=('Marketing_Research.userinfo',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SalesReportOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(verbose_name='填报日期')),
                ('project', models.CharField(max_length=255, verbose_name='项目')),
                ('desc', models.TextField(max_length=255, verbose_name='工作简述')),
                ('type', models.CharField(max_length=255, verbose_name='工作类型')),
                ('state', models.CharField(max_length=255, verbose_name='最新推进状态')),
                ('stage', models.CharField(choices=[('线索获取', '线索获取'), ('线索验证/建档', '线索验证/建档'), ('商机立项', '商机立项'), ('需求调研', '需求调研'), ('方案/报价', '方案/报价'), ('测试/验证', '测试/验证'), ('准入/关键人认可', '准入/关键人认可'), ('商务谈判', '商务谈判'), ('招采/挂网/比选', '招采/挂网/比选'), ('中标/赢单', '中标/赢单'), ('装机/验收', '装机/验收'), ('收单', '收单')], max_length=255, verbose_name='已完成阶段')),
                ('date2', models.DateField(null=True, verbose_name='上一阶段反馈时间')),
                ('date3', models.DateField(null=True, verbose_name='最近计划反馈时间')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '旧销售日报(迁移用)',
                'db_table': 'marketing_research_v2"."JcReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='客户名称')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='所属区域')),
                ('customer_type', models.CharField(choices=[('hospital', '医院'), ('dealer', '经销商'), ('other', '其他')], default='hospital', max_length=50, verbose_name='客户类型')),
                ('level', models.CharField(blank=True, choices=[('A', 'A类客户'), ('B', 'B类客户'), ('C', 'C类客户')], default='C', max_length=10, verbose_name='客户级别')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='关键联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'db_table': 'marketing_research_v2"."Customer',
                'ordering': ['-updatetime'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('project_code', models.CharField(help_text='自动生成或手动输入，用于唯一标识项目', max_length=100, unique=True, verbose_name='项目编号')),
                ('current_stage', models.CharField(choices=[('线索获取', '线索获取'), ('线索验证/建档', '线索验证/建档'), ('商机立项', '商机立项'), ('需求调研', '需求调研'), ('方案/报价', '方案/报价'), ('测试/验证', '测试/验证'), ('准入/关键人认可', '准入/关键人认可'), ('商务谈判', '商务谈判'), ('招采/挂网/比选', '招采/挂网/比选'), ('中标/赢单', '中标/赢单'), ('装机/验收', '装机/验收'), ('收单', '收单')], default='线索获取', max_length=50, verbose_name='当前阶段')),
                ('status', models.CharField(choices=[('active', '进行中'), ('won', '已赢单'), ('lost', '已流失'), ('suspended', '暂停跟进')], default='active', max_length=20, verbose_name='项目状态')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预计金额(元)')),
                ('win_probability', models.IntegerField(default=0, help_text='0-100之间的整数', verbose_name='赢单概率(%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='预计成交时间')),
                ('actual_close_date', models.DateField(blank=True, null=True, verbose_name='实际成交时间')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='SALESREPORT.company', verbose_name='所属公司')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='SALESREPORT.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(db_column='operator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_projects', to='SALESREPORT.reportuserinfo', verbose_name='最后操作人')),
                ('salesman', models.ForeignKey(db_column='salesman', on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to='SALESREPORT.reportuserinfo', verbose_name='负责销售')),
                ('team_members', models.ManyToManyField(blank=True, related_name='participated_projects', to='SALESREPORT.reportuserinfo', verbose_name='协同人员')),
            ],
            options={
                'verbose_name': '项目/商机',
                'verbose_name_plural': '项目管理',
                'db_table': 'marketing_research_v2"."SalesProject',
                'ordering': ['-updatetime'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('线索获取', '线索获取'), ('线索验证/建档', '线索验证/建档'), ('商机立项', '商机立项'), ('需求调研', '需求调研'), ('方案/报价', '方案/报价'), ('测试/验证', '测试/验证'), ('准入/关键人认可', '准入/关键人认可'), ('商务谈判', '商务谈判'), ('招采/挂网/比选', '招采/挂网/比选'), ('中标/赢单', '中标/赢单'), ('装机/验收', '装机/验收'), ('收单', '收单')], help_text='首次创建项目时为空', max_length=50, null=True, verbose_name='原阶段')),
                ('to_stage', models.CharField(choices=[('线索获取', '线索获取'), ('线索验证/建档', '线索验证/建档'), ('商机立项', '商机立项'), ('需求调研', '需求调研'), ('方案/报价', '方案/报价'), ('测试/验证', '测试/验证'), ('准入/关键人认可', '准入/关键人认可'), ('商务谈判', '商务谈判'), ('招采/挂网/比选', '招采/挂网/比选'), ('中标/赢单', '中标/赢单'), ('装机/验收', '装机/验收'), ('收单', '收单')], max_length=50, verbose_name='新阶段')),
                ('change_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('days_in_previous_stage', models.IntegerField(default=0, help_text='在原阶段停留的天数', verbose_name='上一阶段停留天数')),
                ('change_reason', models.TextField(blank=True, help_text='阶段推进的关键事件或原因', verbose_name='变更原因/说明')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('operator', models.ForeignKey(db_column='operator', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SALESREPORT.reportuserinfo', verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_histories', to='SALESREPORT.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '阶段变更记录',
                'verbose_name_plural': '项目阶段历史',
                'db_table': 'marketing_research_v2"."ProjectStageHistory',
                'ordering': ['-change_time'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(verbose_name='填报日期')),
                ('desc', models.TextField(max_length=1000, verbose_name='工作简述')),
                ('type', models.CharField(help_text='如：客户拜访、电话沟通、方案准备等', max_length=255, verbose_name='工作类型')),
                ('state', models.CharField(help_text='本次工作的具体进展', max_length=255, verbose_name='最新推进状态')),
                ('last_feedback_date', models.DateField(blank=True, null=True, verbose_name='上一阶段反馈时间')),
                ('next_plan_date', models.DateField(blank=True, null=True, verbose_name='下次计划跟进时间')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.CASCADE, to='SALESREPORT.company', verbose_name='公司')),
                ('operator', models.ForeignKey(db_column='operator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operatorreport', to='SALESREPORT.reportuserinfo', verbose_name='最后操作人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='SALESREPORT.project', verbose_name='关联项目')),
                ('salesman', models.ForeignKey(db_column='salesman', on_delete=django.db.models.deletion.PROTECT, related_name='salesmanreport', to='SALESREPORT.reportuserinfo', verbose_name='填报人')),
            ],
            options={
                'verbose_name': '销售日报',
                'verbose_name_plural': '销售日报管理',
                'db_table': 'marketing_research_v2"."SalesReport',
                'ordering': ['-date1', '-createtime'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code'], name='SalesProjec_project_94e095_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['salesman', 'status'], name='SalesProjec_salesma_ac5518_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['current_stage'], name='SalesProjec_current_c38aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstagehistory',
            index=models.Index(fields=['project', '-change_time'], name='ProjectStag_project_d55caf_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['project', '-date1'], name='SalesReport_project_7f4ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['salesman', '-date1'], name='SalesReport_salesma_3709a3_idx'),
        ),
    ]
