# Generated by Django 5.2.9 on 2025-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALESREPORT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='项目赢单后的实际成交金额', max_digits=12, null=True, verbose_name='实际成交金额(元)'),
        ),
        migrations.AddField(
            model_name='project',
            name='competitor_info',
            field=models.CharField(blank=True, help_text='如因竞争对手失败，记录竞争对手信息', max_length=200, null=True, verbose_name='主要竞争对手'),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_resume_date',
            field=models.DateField(blank=True, help_text='预计恢复跟进的时间', null=True, verbose_name='预计恢复时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='lost_detail',
            field=models.TextField(blank=True, help_text='详细描述项目流失的原因和经过', null=True, verbose_name='流失详细说明'),
        ),
        migrations.AddField(
            model_name='project',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('price', '价格因素'), ('competitor', '竞争对手中标'), ('budget_cancel', '客户预算取消'), ('product_mismatch', '产品不符合需求'), ('timing', '时机不合适'), ('other', '其他')], help_text='项目输单时的主要原因', max_length=50, null=True, verbose_name='流失原因'),
        ),
        migrations.AddField(
            model_name='project',
            name='lost_stage',
            field=models.CharField(blank=True, choices=[('线索获取', '线索获取'), ('线索验证/建档', '线索验证/建档'), ('商机立项', '商机立项'), ('需求调研', '需求调研'), ('方案/报价', '方案/报价'), ('测试/验证', '测试/验证'), ('准入/关键人认可', '准入/关键人认可'), ('商务谈判', '商务谈判'), ('招采/挂网/比选', '招采/挂网/比选'), ('中标/赢单', '中标/赢单'), ('装机/验收', '装机/验收'), ('收单', '收单')], help_text='项目流失时所处的销售阶段，用于分析各阶段流失率', max_length=50, null=True, verbose_name='流失时所在阶段'),
        ),
        migrations.AddField(
            model_name='project',
            name='suspend_reason',
            field=models.TextField(blank=True, help_text='项目暂停跟进的原因', null=True, verbose_name='暂停原因'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='last_feedback_date',
            field=models.DateField(blank=True, help_text='此字段已弃用，请使用ProjectStageHistory查询阶段历史', null=True, verbose_name='上一阶段反馈时间（已弃用）'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='state',
            field=models.CharField(blank=True, help_text='本次工作的具体进展', max_length=255, verbose_name='最新推进状态'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='type',
            field=models.CharField(blank=True, choices=[('stage_advance', '阶段推进'), ('customer_visit', '客户拜访'), ('phone_call', '电话沟通'), ('proposal_prep', '方案准备'), ('tech_demo', '技术演示'), ('negotiation', '商务谈判'), ('internal_coord', '内部协调'), ('bid_prep', '招标准备'), ('other', '其他')], help_text='销售活动的类型', max_length=50, verbose_name='活动类型'),
        ),
    ]
