# Generated by Django 3.2 on 2025-08-15 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SALESREPORT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreport',
            options={'managed': False, 'verbose_name_plural': '集成业务日报'},
        ),
    ]
