# Generated by Django 5.2.9 on 2025-12-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SALESREPORT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreport',
            options={'managed': True, 'verbose_name_plural': '集成业务日报'},
        ),
    ]
