# Generated by Django 5.2.9 on 2025-12-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALESREPORT', '0003_migrate_activity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='type',
            field=models.CharField(blank=True, choices=[('stage_advance', '🎯 阶段推进'), ('customer', '👥 客户活动'), ('internal', '📝 内部工作')], help_text='销售活动的类型', max_length=50, verbose_name='活动类型'),
        ),
    ]
