# Generated by Django 5.2.9 on 2025-12-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALESREPORT', '0005_convert_to_chinese_activity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='type',
            field=models.CharField(blank=True, choices=[('阶段推进', '🎯 阶段推进'), ('客户活动', '👥 客户活动'), ('内部工作', '📝 内部工作')], help_text='销售活动的类型', max_length=50, verbose_name='活动类型'),
        ),
    ]
