# Generated by Django 3.2 on 2023-03-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器品牌')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '品牌列表',
                'db_table': 'marketing_research_v2"."Brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('黄浦', '黄浦'), ('徐汇', '徐汇'), ('长宁', '长宁'), ('静安', '静安'), ('普陀', '普陀'), ('虹口', '虹口'), ('杨浦', '杨浦'), ('浦东', '浦东'), ('闵行', '闵行'), ('宝山', '宝山'), ('嘉定', '嘉定'), ('金山', '金山'), ('松江', '松江'), ('青浦', '青浦'), ('奉贤', '奉贤'), ('崇明', '崇明')], max_length=255, verbose_name='区域')),
                ('hospitalclass', models.CharField(choices=[('三级', '三级'), ('二级', '二级'), ('一级', '一级'), ('未定级', '未定级')], max_length=255, verbose_name='医院级别')),
                ('hospitalname', models.CharField(max_length=255, verbose_name='医院名称')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '医院列表',
                'db_table': 'marketing_research_v2"."Hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JCResearchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=255, verbose_name='院长')),
                ('sizeofclinicallab', models.CharField(max_length=255, verbose_name='检验科规模')),
                ('jcornot', models.CharField(choices=[('是', '是'), ('否', '否'), ('未知', '未知')], max_length=255, verbose_name='是否集约化配送')),
                ('jccompany', models.CharField(max_length=255, verbose_name='集约化配送公司')),
                ('jcstartdate', models.DateField(blank=True, help_text='例: 2023/02/01', null=True, verbose_name='集约化配送开始时间')),
                ('jcenddate', models.DateField(blank=True, help_text='例: 2023/02/01', null=True, verbose_name='集约化配送截止时间')),
                ('jcmemo', models.CharField(choices=[('是', '是'), ('否', '否'), ('未知', '未知')], max_length=255, verbose_name='集约化配送备注')),
                ('sizeofsystem', models.CharField(max_length=255, verbose_name='生化免疫流水线规模')),
                ('systemstartdate', models.DateField(blank=True, help_text='例: 2023/02/01', null=True, verbose_name='流水线合作开始时间')),
                ('systemenddate', models.DateField(blank=True, help_text='例: 2023/02/01', null=True, verbose_name='流水线合作截止时间')),
                ('systemmemo', models.CharField(max_length=255, verbose_name='流水线备注')),
                ('relation', models.CharField(max_length=255, verbose_name='关系点')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('brand', models.ForeignKey(db_column='brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research_JC.brand', verbose_name='品牌')),
                ('hospital', models.ForeignKey(db_column='hospital', on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research_JC.hospital', verbose_name='医院')),
            ],
            options={
                'verbose_name_plural': '集成调研表',
                'db_table': 'marketing_research_v2"."JCResearchList',
            },
        ),
    ]
