# Generated by Django 3.2 on 2023-03-19 14:14

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0009_alter_hospital_district'),
        ('Marketing_Research_JC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfojc',
            fields=[
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'db_table': 'django_admin_v2"."auth_user',
                'managed': False,
                'proxy': True,
            },
            bases=('Marketing_Research.userinfo',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='jcresearchlist',
            name='operator',
            field=models.ForeignKey(db_column='operator', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operatorjc', to='Marketing_Research_JC.userinfojc', verbose_name='最后操作人'),
        ),
    ]
