# Generated by Django 3.2 on 2023-03-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_JC', '0002_auto_20230319_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcresearchlist',
            name='operator',
            field=models.ForeignKey(db_column='operator', on_delete=django.db.models.deletion.CASCADE, related_name='operatorjc', to='Marketing_Research_JC.userinfojc', verbose_name='最后操作人'),
        ),
    ]
