# Generated by Django 3.2 on 2023-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_JC', '0004_auto_20230319_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcresearchlist',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='院长'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='jccompany',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='集约化配送公司'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='jcmemo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='集约化配送备注'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='relation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关系点'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='sizeofclinicallab',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='检验科规模'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='sizeofsystem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生化免疫流水线规模'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='systemmemo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='流水线备注'),
        ),
    ]
