# Generated by Django 3.2 on 2023-03-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_JC', '0006_alter_jcresearchlist_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcresearchlist',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='院长姓名'),
        ),
    ]
