# Generated by Django 3.2 on 2023-03-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_JC', '0007_alter_jcresearchlist_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcresearchlist',
            name='jccompany',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='集成配送公司'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='jcenddate',
            field=models.DateField(blank=True, help_text='例: 2023/02/01', null=True, verbose_name='集成截止时间'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='jcmemo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='集成备注'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='jcornot',
            field=models.CharField(choices=[('是', '是'), ('否', '否'), ('未知', '未知')], max_length=255, verbose_name='是否集成'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='jcstartdate',
            field=models.DateField(blank=True, help_text='例: 2023/02/01', null=True, verbose_name='集成开始时间'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='systemenddate',
            field=models.DateField(blank=True, help_text='例: 2023/02/01', null=True, verbose_name='流水线截止时间'),
        ),
        migrations.AlterField(
            model_name='jcresearchlist',
            name='systemstartdate',
            field=models.DateField(blank=True, help_text='例: 2023/02/01', null=True, verbose_name='流水线开始时间'),
        ),
    ]
