# Generated by Django 3.2 on 2023-12-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式')),
                ('payterm', models.CharField(blank=True, max_length=255, null=True, verbose_name='账期')),
                ('tax', models.CharField(blank=True, max_length=255, null=True, verbose_name='税率')),
                ('delivery', models.CharField(blank=True, max_length=255, null=True, verbose_name='配送方式')),
                ('project', models.CharField(max_length=255, verbose_name='项目')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '供应商基础信息汇总表',
                'db_table': 'SUPPLIERS"."Supplier_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='XEY_Supplier_Product_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.BigIntegerField(verbose_name='排行')),
                ('supplier', models.CharField(max_length=255, verbose_name='供应商')),
                ('contact', models.CharField(max_length=255, verbose_name='联系方式')),
                ('payterm', models.CharField(max_length=255, verbose_name='账期')),
                ('tax', models.CharField(max_length=255, verbose_name='税率')),
                ('delivery', models.CharField(max_length=255, verbose_name='配送方式')),
                ('productcode', models.CharField(max_length=255, verbose_name='产品编码')),
                ('productname', models.CharField(max_length=255, verbose_name='产品名称')),
                ('spec', models.CharField(max_length=255, verbose_name='规格')),
                ('unit', models.CharField(max_length=255, verbose_name='单位')),
                ('brand', models.CharField(max_length=255, verbose_name='品牌')),
                ('recentdate', models.DateField(verbose_name='发票日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='单价')),
                ('qty21', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='21年数量')),
                ('qty22', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='22年数量')),
                ('qty23', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='23年数量')),
                ('qty24', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='24年数量')),
                ('totalqty', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='总数量')),
                ('sum21', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='21年销售额')),
                ('sum22', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='21年销售额')),
                ('sum23', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='21年销售额')),
                ('sum24', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='21年销售额')),
                ('totalsum', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='总销售额')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('project', models.CharField(default='徐二院', max_length=255, verbose_name='项目')),
            ],
            options={
                'verbose_name_plural': '徐二院供应商销量明细',
                'db_table': 'SUPPLIERS"."XEY_Supplier_Product_Summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='XEY_Supplier_Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(verbose_name='排行')),
                ('supplier', models.CharField(max_length=255, verbose_name='供应商')),
                ('qty21', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='21年数量')),
                ('qty22', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='22年数量')),
                ('qty23', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='23年数量')),
                ('qty24', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='24年数量')),
                ('totalqty', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='总数量')),
                ('sum21', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='21年销售额')),
                ('sum22', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='21年销售额')),
                ('sum23', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='21年销售额')),
                ('sum24', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='21年销售额')),
                ('totalsum', models.DecimalField(decimal_places=2, max_digits=25, null=True, verbose_name='总销售额')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('project', models.CharField(default='徐二院', max_length=255, verbose_name='项目')),
            ],
            options={
                'verbose_name_plural': '徐二院供应商销量排行',
                'db_table': 'SUPPLIERS"."XEY_Supplier_Rank',
                'managed': False,
            },
        ),
    ]
