# Generated by Django 3.2 on 2023-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NANXIANG', '0002_auto_20230801_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nxmenu',
            name='purchaseqty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月销售数量'),
        ),
        migrations.AlterField(
            model_name='nxmenu',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月销售成本'),
        ),
        migrations.AlterField(
            model_name='nxmenu',
            name='theoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='毛利润'),
        ),
        migrations.AlterField(
            model_name='nxmenu',
            name='theoreticalgppercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='毛利率'),
        ),
        migrations.AlterField(
            model_name='nxmenu',
            name='theoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月销售金额'),
        ),
        migrations.AlterField(
            model_name='nxmenuforinline',
            name='purchaseqty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月销售数量'),
        ),
        migrations.AlterField(
            model_name='nxmenuforinline',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月销售成本'),
        ),
        migrations.AlterField(
            model_name='nxmenuforinline',
            name='theoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='毛利润'),
        ),
        migrations.AlterField(
            model_name='nxmenuforinline',
            name='theoreticalgppercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='毛利率'),
        ),
        migrations.AlterField(
            model_name='nxmenuforinline',
            name='theoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月销售金额'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='项目1-6月销售成本'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='purchasesumpercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='该项目占总成本占比'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='purchasesumpercentinproject',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='项目中各供应商成本占比'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='supplierpurchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='供应商1-6月销售成本'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='suppliertheoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='供应商毛利润'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='suppliertheoreticalgppercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='供应商毛利率'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='suppliertheoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='供应商销售额'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='theoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='项目毛利润'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='theoreticalgppercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='项目毛利率'),
        ),
        migrations.AlterField(
            model_name='nxoverall',
            name='theoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='项目销售额'),
        ),
    ]
