# Generated by Django 3.2 on 2023-07-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='endsupplier',
            field=models.CharField(blank=True, help_text='如果是普美瑞下面的代理商，写成:普美瑞-XXX', max_length=255, null=True, verbose_name='代理商名称'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='sumpermonth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='月产出额'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='testprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='代理商价格'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='testspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='该品牌月测试数'),
        ),
        migrations.AlterField(
            model_name='gsmrsalestarget',
            name='q1actualsales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Q1实际完成额'),
        ),
        migrations.AlterField(
            model_name='gsmrsalestarget',
            name='q2actualsales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Q2实际完成额'),
        ),
        migrations.AlterField(
            model_name='gsmrsalestarget',
            name='q3actualsales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Q3实际完成额'),
        ),
        migrations.AlterField(
            model_name='gsmrsalestarget',
            name='q4actualsales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Q4实际完成额'),
        ),
    ]
