# Generated by Django 3.2 on 2023-03-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsmrresearchlist',
            name='firsttierdistribution',
        ),
        migrations.RemoveField(
            model_name='gsmrresearchlist',
            name='secondtierdistribution',
        ),
        migrations.AddField(
            model_name='gsmrresearchdetail',
            name='firsttierdistribution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='一级代理'),
        ),
        migrations.AddField(
            model_name='gsmrresearchdetail',
            name='secondtierdistribution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='二级代理'),
        ),
    ]
