# Generated by Django 3.2 on 2023-07-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0002_auto_20230712_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmrdetailcalculate',
            name='ownsalespercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='月产出额占比'),
        ),
        migrations.AddField(
            model_name='gsmrdetailcalculate',
            name='ownsalespermonth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='国赛美瑞招商月产出额'),
        ),
        migrations.AddField(
            model_name='gsmrdetailcalculate',
            name='salespermonth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='总月产出额'),
        ),
        migrations.AddField(
            model_name='gsmrdetailcalculate',
            name='testspermonthcombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='品牌集合'),
        ),
        migrations.AlterField(
            model_name='gsmrdetailcalculate',
            name='ownmachinenumber',
            field=models.PositiveIntegerField(default=0, verbose_name='国赛仪器总数'),
        ),
        migrations.AlterField(
            model_name='gsmrdetailcalculate',
            name='ownmachinepercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='仪器数占比'),
        ),
        migrations.AlterField(
            model_name='gsmrdetailcalculate',
            name='owntestspercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='测试数占比'),
        ),
        migrations.AlterField(
            model_name='gsmrdetailcalculate',
            name='owntestspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='国赛月测试数'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='machinenumber',
            field=models.PositiveIntegerField(default=1, verbose_name='仪器数量'),
        ),
    ]
