# Generated by Django 3.2 on 2023-07-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0003_auto_20230713_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmrresearchdetail',
            name='type',
            field=models.CharField(choices=[('非我司业务', '非我司业务'), ('国赛美瑞-招商', '国赛美瑞-招商'), ('普美瑞-招商', '普美瑞-招商'), ('普美瑞-直销', '普美瑞-直销'), ('普美瑞-集成', '普美瑞-集成')], default='非我司业务', max_length=25, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='gsmrdetailcalculate',
            name='ownsalespermonth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True, verbose_name='国赛美瑞招商月产出额'),
        ),
        migrations.AlterField(
            model_name='gsmrdetailcalculate',
            name='salespermonth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True, verbose_name='总月产出额'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='endsupplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='代理商名称'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='installdate',
            field=models.DateField(blank=True, help_text='例:2023/07/01,如有多台，填最老的那台', null=True, verbose_name='装机日期'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='sumpermonth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='国赛美瑞-招商的业务，此处必填', max_digits=25, null=True, verbose_name='月产出额'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='testprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=25, null=True, verbose_name='代理商价格'),
        ),
    ]
