# Generated by Django 3.2 on 2023-04-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0005_branddelete_companydelete_competitionrelationdelete_gsmrdetailcalculatedelete_gsmrprojectdetaildelet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='competitionrelation',
            field=models.ForeignKey(blank=True, db_column='competitionrelation', null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research_ZS.competitionrelation', verbose_name='竞品关系点'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='machinenumber',
            field=models.PositiveIntegerField(default=0, verbose_name='仪器数量'),
        ),
    ]
