# Generated by Django 3.2 on 2023-07-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0006_auto_20230713_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmrresearchlist',
            name='memo',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='gsmrresearchlist',
            name='relation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='关系梳理'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='installdate',
            field=models.DateField(blank=True, help_text='例:2023/07/01', null=True, verbose_name='装机日期'),
        ),
    ]
