# Generated by Django 3.2 on 2023-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0007_alter_gsmrresearchlist_salesmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='detailedprojecttestspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='细分项目月测试数(人份)'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchlist',
            name='testspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='总体月测试数(人份)'),
        ),
    ]
