# Generated by Django 3.2 on 2023-07-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0007_auto_20230713_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmrdetailcalculate',
            name='progresshistory',
            field=models.JSONField(blank=True, null=True, verbose_name='历史进展'),
        ),
        migrations.AddField(
            model_name='gsmrresearchlist',
            name='progress',
            field=models.CharField(blank=True, choices=[('待拜访', '待拜访'), ('初期了解中', '初期了解中'), ('有意向', '有意向'), ('申报预算', '申报预算'), ('审批中', '审批中'), ('审批通过', '审批通过'), ('待招标', '待招标'), ('招标完成', '招标完成'), ('仪器装机启用', '仪器装机启用'), ('仪器试剂均开票', '仪器试剂均开票')], default='待拜访', max_length=25, null=True, verbose_name='进展(新项目必选)'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchdetail',
            name='testprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='GSMR卖给代理商的价格，非GSMR招商业务可不填', max_digits=25, null=True, verbose_name='代理商价格'),
        ),
    ]
