# Generated by Django 3.2 on 2023-04-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0008_auto_20230423_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmrdetailcalculate',
            name='machinenumbercombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器数量集合'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchlist',
            name='testspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='月总测试数(人份)'),
        ),
    ]
