# Generated by Django 3.2 on 2023-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0008_auto_20230717_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmrresearchlist',
            name='progress',
            field=models.CharField(blank=True, choices=[('待拜访', '待拜访'), ('初期了解中', '初期了解中'), ('有意向', '有意向'), ('申报预算', '申报预算'), ('审批中', '审批中'), ('审批通过', '审批通过'), ('待招标', '待招标'), ('招标完成', '招标完成'), ('仪器装机启用', '仪器装机启用'), ('仪器试剂均开票', '仪器试剂均开票')], max_length=25, null=True, verbose_name='进展(新项目必选)'),
        ),
    ]
