# Generated by Django 3.2 on 2023-07-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research_ZS', '0009_alter_gsmrresearchlist_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmrdetailcalculate',
            name='newold',
            field=models.CharField(blank=True, default='新商机', max_length=255, null=True, verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='gsmrdetailcalculate',
            name='testspermonthcombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='测试数集合'),
        ),
        migrations.AlterField(
            model_name='gsmrresearchlist',
            name='progress',
            field=models.CharField(blank=True, choices=[('待拜访', '待拜访'), ('初期了解中', '初期了解中'), ('有意向', '有意向'), ('申报预算', '申报预算'), ('审批中', '审批中'), ('审批通过', '审批通过'), ('待招标', '待招标'), ('招标完成', '招标完成'), ('仪器装机启用', '仪器装机启用'), ('仪器试剂均开票', '仪器试剂均开票')], help_text='仅针对新项目，每点击一次下方的“保存”，都会记录一次进展，注意不要选错', max_length=25, null=True, verbose_name='进展(新项目必选)'),
        ),
    ]
