# Generated by Django 3.2 on 2023-06-09 01:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0004_auto_20230609_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pzxoverall',
            name='whygrowth',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('新开项目', '新开项目'), ('供应商重新谈判', '供应商重新谈判'), ('渠道变更', '渠道变更'), ('品牌替换', '品牌替换'), ('套餐绑定', '套餐绑定')], help_text='（增量来源可以多选, 选后请在下方填写明细）', max_length=25, verbose_name='增量来源'),
        ),
    ]
