# Generated by Django 3.2 on 2023-06-14 14:07

import django.contrib.postgres.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0005_alter_pzxoverall_whygrowth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pzxnegotiationdetail',
            name='skuhistory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='历史sku'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='whygrowth',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('新开项目', '新开项目'), ('供应商重新谈判', '供应商重新谈判'), ('渠道变更', '渠道变更'), ('品牌替换', '品牌替换'), ('套餐绑定', '套餐绑定')], help_text='（按住Ctrl键可多选, 选择后, 请在下方填写每一个增量来源的详情）', max_length=25, verbose_name='增量来源'),
        ),
    ]
