# Generated by Django 3.2 on 2023-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0006_auto_20230614_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pzxchangebrandstatus',
            name='actionplan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AddField(
            model_name='pzxchangechannelstatus',
            name='actionplan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AddField(
            model_name='pzxnegotiationstatus',
            name='actionplan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AddField(
            model_name='pzxnewprojectstatus',
            name='actionplan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='actionplan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AddField(
            model_name='pzxsetstatus',
            name='actionplan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
    ]
