# Generated by Django 3.2 on 2023-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0007_auto_20230615_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='pzxoverall',
            name='monthgpgrowthdetail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='月毛利额增量预估'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='thisyeargpgrowthdetail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='23年毛利额增量预估/元'),
        ),
        migrations.AlterField(
            model_name='pzxchangebrandstatus',
            name='actionplan',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AlterField(
            model_name='pzxchangechannelstatus',
            name='actionplan',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationstatus',
            name='actionplan',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AlterField(
            model_name='pzxnewprojectstatus',
            name='actionplan',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='monthgpgrowth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='月毛利额增量预估总计/元'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='thisyeargpgrowth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='23年毛利额增量预估总计/元'),
        ),
        migrations.AlterField(
            model_name='pzxsetstatus',
            name='actionplan',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='行动计划'),
        ),
    ]
