# Generated by Django 3.2 on 2023-06-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0008_auto_20230615_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='pzxmenu',
            name='category1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='科室'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='category2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='使用科室'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='overallid',
            field=models.ForeignKey(db_column='overallid', default=1, on_delete=django.db.models.deletion.CASCADE, to='PUZHONGXIN.pzxoverall', verbose_name='主表id'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='priceperunit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='销售价/单位'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='使用科室'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='purchaseqty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='今年以来采购数量'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='今年以来采购金额（订单跟踪）'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='theoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论毛利润'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='theoreticalgppercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论毛利率'),
        ),
        migrations.AddField(
            model_name='pzxmenu',
            name='theoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论销售金额（根据售价反推）'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='23年采购总额'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='theoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论毛利润'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='theoreticalgppercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论毛利率'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='theoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论销售额'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='usagedepartment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='使用科室'),
        ),
        migrations.AlterField(
            model_name='pzxmenu',
            name='costperunit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='采购价/单位'),
        ),
    ]
