# Generated by Django 3.2 on 2023-06-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0009_auto_20230615_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pzxmenu',
            name='overallid',
        ),
        migrations.AlterField(
            model_name='pzxmenu',
            name='category1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='大类'),
        ),
        migrations.AlterField(
            model_name='pzxmenu',
            name='category2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='小类'),
        ),
        migrations.AlterField(
            model_name='pzxmenu',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='项目大类'),
        ),
        migrations.CreateModel(
            name='PZXMenuforinline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='普中心', max_length=255, verbose_name='客户')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='科室')),
                ('semidepartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='使用科室')),
                ('category1', models.CharField(blank=True, max_length=255, null=True, verbose_name='大类')),
                ('category2', models.CharField(blank=True, max_length=255, null=True, verbose_name='小类')),
                ('project', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目大类')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品编码U8')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称U8')),
                ('spec', models.CharField(blank=True, max_length=255, null=True, verbose_name='规格')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='单位')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='品牌')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('costperunit', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='采购价/单位')),
                ('priceperunit', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='销售价/单位')),
                ('purchaseqty', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='今年以来采购数量')),
                ('purchasesum', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='今年以来采购金额（订单跟踪）')),
                ('theoreticalvalue', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论销售金额（根据售价反推）')),
                ('theoreticalgp', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论毛利润')),
                ('theoreticalgppercent', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论毛利率')),
                ('machinemodel', models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器型号')),
                ('machinebrand', models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器品牌')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('overallid', models.ForeignKey(db_column='overallid', default=1, on_delete=django.db.models.deletion.CASCADE, to='PUZHONGXIN.pzxoverall', verbose_name='主表id')),
            ],
            options={
                'verbose_name_plural': 'SPD普中心大菜单作为inline',
                'db_table': 'marketing_research_v2"."SPDPZXMenuforinline',
            },
        ),
    ]
