# Generated by Django 3.2 on 2023-06-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0010_auto_20230615_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pzxoverall',
            old_name='usagedepartment',
            new_name='semidepartment',
        ),
    ]
