# Generated by Django 3.2 on 2023-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0012_auto_20230620_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliervalue',
            name='suppliervalueid',
        ),
        migrations.RemoveField(
            model_name='pzxoverall',
            name='projectvalueid',
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='项目1-6月采购总额'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='purchasesumpercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='该项目占总采购额%'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='purchasesumpercentinproject',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='该项目占总采购额%'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='supplierpurchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='项目1-6月采购总额'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='suppliertheoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论毛利润'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='suppliertheoreticalgppercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='理论毛利率'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='suppliertheoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论销售额'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='theoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论毛利润'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='theoreticalgppercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='理论毛利率'),
        ),
        migrations.AddField(
            model_name='pzxoverall',
            name='theoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='理论销售额'),
        ),
        migrations.DeleteModel(
            name='ProjectValue',
        ),
        migrations.DeleteModel(
            name='SupplierValue',
        ),
    ]
