# Generated by Django 3.2 on 2023-06-25 06:44

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0013_auto_20230621_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pzxnegotiationdetail',
            name='skuhistory',
        ),
        migrations.AlterField(
            model_name='pzxmenu',
            name='purchaseqty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月采购数量'),
        ),
        migrations.AlterField(
            model_name='pzxmenu',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月采购金额（订单跟踪）'),
        ),
        migrations.AlterField(
            model_name='pzxmenuforinline',
            name='purchaseqty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月采购数量'),
        ),
        migrations.AlterField(
            model_name='pzxmenuforinline',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='1-6月采购金额（订单跟踪）'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='costfeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='原采购价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='gppercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='lispercent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='LIS结算比例(必填,≤1)'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='lissettleprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='LIS结算价'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='marketpricefeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='市场价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='newcostdroprate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新采购价下降比例'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='newcostfeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新采购价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='newgppercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxnegotiationdetail',
            name='targetdropdate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='谈判下降比例'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='purchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='项目1-6月采购额'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='purchasesumpercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='该项目占总采购额占比'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='purchasesumpercentinproject',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='项目中各供应商采购额占比'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='supplierpurchasesum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='供应商1-6月采购额'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='suppliertheoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='供应商理论毛利润'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='suppliertheoreticalgppercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='供应商理论毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='suppliertheoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='供应商理论销售额'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='theoreticalgp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='项目理论毛利润'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='theoreticalgppercent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25, verbose_name='项目理论毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='theoreticalvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='项目理论销售额'),
        ),
        migrations.AlterField(
            model_name='pzxoverall',
            name='whygrowth',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('新开项目', '新开项目'), ('供应商重新谈判', '供应商重新谈判'), ('渠道变更', '渠道变更'), ('品牌替换', '品牌替换'), ('套餐绑定', '套餐绑定'), ('--', '--')], help_text='（按住Ctrl键可多选, 选择后, 请在下方填写每一个增量来源的详情）', max_length=25, verbose_name='增量来源'),
        ),
    ]
