# Generated by Django 3.2 on 2023-06-26 02:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PUZHONGXIN', '0016_auto_20230625_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='pzxbeforechangebranddetail',
            name='productid',
            field=models.ForeignKey(blank=True, db_column='productid', null=True, on_delete=django.db.models.deletion.CASCADE, to='PUZHONGXIN.pzxmenu', verbose_name='产品信息:名称_规格_单位_采购价_供应商_品牌'),
        ),
        migrations.AddField(
            model_name='pzxbeforechangebranddetail',
            name='skuhistory',
            field=models.JSONField(blank=True, null=True, verbose_name='历史sku'),
        ),
        migrations.AlterField(
            model_name='pzxafterchangebranddetail',
            name='costfeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='原采购价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxafterchangebranddetail',
            name='gppercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxafterchangebranddetail',
            name='marketpricefeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='市场价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxafterchangebranddetail',
            name='newcostdroprate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新采购价下降比例'),
        ),
        migrations.AlterField(
            model_name='pzxafterchangebranddetail',
            name='newcostfeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新采购价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxafterchangebranddetail',
            name='newgppercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxafterchangebranddetail',
            name='targetdropdate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='谈判下降比例'),
        ),
        migrations.AlterField(
            model_name='pzxbeforechangebranddetail',
            name='costfeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='原采购价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxbeforechangebranddetail',
            name='gppercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxbeforechangebranddetail',
            name='lissettleprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='LIS结算价'),
        ),
        migrations.AlterField(
            model_name='pzxbeforechangebranddetail',
            name='newcostdroprate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新采购价下降比例'),
        ),
        migrations.AlterField(
            model_name='pzxbeforechangebranddetail',
            name='newcostfeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新采购价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxbeforechangebranddetail',
            name='newgppercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxbeforechangebranddetail',
            name='targetdropdate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='谈判下降比例'),
        ),
        migrations.AlterField(
            model_name='pzxchangechanneldetail',
            name='lissettleprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='LIS结算价'),
        ),
        migrations.AlterField(
            model_name='pzxsetdetail',
            name='costfeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='原采购价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxsetdetail',
            name='gppercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxsetdetail',
            name='marketpricefeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='市场价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxsetdetail',
            name='newcostdroprate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新采购价下降比例'),
        ),
        migrations.AlterField(
            model_name='pzxsetdetail',
            name='newcostfeepercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新采购价占收费比例'),
        ),
        migrations.AlterField(
            model_name='pzxsetdetail',
            name='newgppercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='新毛利率'),
        ),
        migrations.AlterField(
            model_name='pzxsetdetail',
            name='targetdropdate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True, verbose_name='谈判下降比例'),
        ),
    ]
