# Generated by Django 3.2 on 2023-03-09 16:20

import Marketing_Research.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0002_alter_pmrresearchlist_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmrresearchdetail',
            name='brand',
            field=models.ForeignKey(db_column='brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research.brand', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(db_column='company', default=Marketing_Research.models.get_compmany_default_value, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research.company', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='salesmanposition',
            name='company',
            field=models.ForeignKey(db_column='company', default=Marketing_Research.models.get_compmany_default_value, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research.company', verbose_name='公司'),
        ),
    ]
