# Generated by Django 3.2 on 2023-03-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0003_auto_20230310_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='company',
            field=models.ForeignKey(db_column='company', default=1, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research.company', verbose_name='公司'),
        ),
    ]
