# Generated by Django 3.2 on 2023-03-10 01:32

import Marketing_Research.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0004_projectdetail_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='company',
            field=models.ForeignKey(db_column='company', default=Marketing_Research.models.get_compmany_default_value, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research.company', verbose_name='公司'),
        ),
    ]
