# Generated by Django 3.2 on 2023-03-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0005_alter_projectdetail_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcalculate',
            name='brandscombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='品牌集合'),
        ),
        migrations.AddField(
            model_name='detailcalculate',
            name='competitionrelationcombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='竞品关系点集合'),
        ),
        migrations.AddField(
            model_name='detailcalculate',
            name='installdatescombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='装机时间集合'),
        ),
        migrations.AddField(
            model_name='detailcalculate',
            name='machinemodelcombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器型号集合'),
        ),
        migrations.AddField(
            model_name='detailcalculate',
            name='machineseriescombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='序列号集合'),
        ),
        migrations.AddField(
            model_name='detailcalculate',
            name='ownbusinesscombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='是否我司业务集合'),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='year',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024')], default=2023, max_length=25, verbose_name='年份'),
        ),
    ]
