# Generated by Django 3.2 on 2023-03-15 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0006_auto_20230314_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestarget',
            name='q1target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Q1目标额/元'),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='q2target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Q2目标额/元'),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='q3target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Q3目标额/元'),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='q4target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Q4目标额/元'),
        ),
    ]
