# Generated by Django 3.2 on 2023-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0007_auto_20230315_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcalculate',
            name='detailedprojectcombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='项目细分集合'),
        ),
    ]
