# Generated by Django 3.2 on 2023-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0008_detailcalculate_detailedprojectcombine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(choices=[('黄浦', '黄浦'), ('徐汇', '徐汇'), ('长宁', '长宁'), ('静安', '静安'), ('普陀', '普陀'), ('虹口', '虹口'), ('杨浦', '杨浦'), ('浦东', '浦东'), ('闵行', '闵行'), ('宝山', '宝山'), ('嘉定', '嘉定'), ('金山', '金山'), ('松江', '松江'), ('青浦', '青浦'), ('奉贤', '奉贤'), ('崇明', '崇明')], max_length=255, verbose_name='区域'),
        ),
    ]
