# Generated by Django 3.2 on 2023-03-24 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0009_alter_hospital_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmrresearchdetail',
            name='competitionrelation',
            field=models.ForeignKey(db_column='competitionrelation', null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research.competitionrelation', verbose_name='竞品关系点'),
        ),
        migrations.AlterField(
            model_name='pmrresearchdetail',
            name='detailedproject',
            field=models.ForeignKey(db_column='detailedproject', help_text='例如:本页项目为WAKO,则项目细分为WAKO项目下的具体细分', null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research.projectdetail', verbose_name='项目细分(注意根据本页主项目填报)'),
        ),
    ]
