# Generated by Django 3.2 on 2023-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0011_alter_pmrresearchdetail_machinenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholeresearchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('hospitalclass', models.CharField(blank=True, max_length=255, null=True)),
                ('hospitalname', models.CharField(blank=True, max_length=255, null=True)),
                ('salesman1', models.CharField(blank=True, max_length=255, null=True)),
                ('salesman2', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=25, null=True)),
                ('q1target', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q1completemonth', models.CharField(blank=True, max_length=25, null=True)),
                ('q1actualsales', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q1finishrate', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q2target', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q2completemonth', models.CharField(blank=True, max_length=25, null=True)),
                ('q2actualsales', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q2finishrate', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q3target', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q3completemonth', models.CharField(blank=True, max_length=25, null=True)),
                ('q3actualsales', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q3finishrate', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q4target', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q4completemonth', models.CharField(blank=True, max_length=25, null=True)),
                ('q4actualsales', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('q4finishrate', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('totalmachinenumber', models.IntegerField(blank=True, null=True)),
                ('ownmachinenumber', models.IntegerField(blank=True, null=True)),
                ('ownmachinepercent', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('newold', models.CharField(blank=True, max_length=255, null=True)),
                ('totalsumpermonth', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('researchlist', models.BigIntegerField(blank=True, null=True)),
                ('detailedproject', models.CharField(blank=True, max_length=255, null=True)),
                ('ownbusiness', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('machinemodel', models.CharField(blank=True, max_length=255, null=True)),
                ('machineseries', models.CharField(blank=True, max_length=255, null=True)),
                ('machinenumber', models.IntegerField(blank=True, null=True)),
                ('installdate', models.DateField(blank=True, null=True)),
                ('expiration', models.CharField(blank=True, max_length=255, null=True)),
                ('testprice', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('sumpermonth', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('endsupplier', models.CharField(blank=True, max_length=255, null=True)),
                ('competitionrelation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'marketing_research_v2"."WholeResearchList',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='pmrresearchlist',
            name='salesmode',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='Audio', max_length=25, verbose_name='销售模式'),
        ),
    ]
