# Generated by Django 3.2 on 2023-03-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0018_branddelete_companydelete_competitionrelationdelete_detailcalculatedelete_hospitaldelete_pmrresearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmrresearchlist',
            name='owntestspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='我司业务月测试数'),
        ),
        migrations.AlterField(
            model_name='pmrresearchlist',
            name='testspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='月总测试数'),
        ),
    ]
