# Generated by Django 3.2 on 2023-04-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0019_auto_20230329_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmrresearchdetail',
            name='competitionrelation',
            field=models.ForeignKey(blank=True, db_column='competitionrelation', null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketing_Research.competitionrelation', verbose_name='竞品关系点'),
        ),
    ]
