# Generated by Django 3.2 on 2023-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0021_alter_pmrresearchlist_salesmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmrresearchdetail',
            name='machineseries',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='序列号(我司仪器必填。若序列号未知但共用仪器时,请同时在此填相同的随机5位数字+字母,并不可与其他仪器重复，不然影响计算)'),
        ),
        migrations.AlterField(
            model_name='pmrresearchdetail',
            name='ownbusiness',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, help_text="普美瑞CRP/SAA中的迈瑞品牌为'竞品',选'否'", verbose_name='是否我司业务'),
        ),
        migrations.AlterField(
            model_name='pmrresearchlist',
            name='testspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='月总测试数(人份)'),
        ),
    ]
