# Generated by Django 3.2 on 2023-04-25 08:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0022_auto_20230423_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcalculate',
            name='machinenumbercombine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器数量集合'),
        ),
        migrations.AlterField(
            model_name='pmrresearchlist',
            name='owntestspermonth',
            field=models.PositiveIntegerField(default=0, help_text='注意：此处测试数为人份数, 请填写我司业务的月均人份数，从而了解市场占有率', verbose_name='我司月测试数'),
        ),
        migrations.AlterField(
            model_name='pmrresearchlist',
            name='saleschannel',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='销售路径及进展'),
        ),
        migrations.AlterField(
            model_name='pmrresearchlist',
            name='salesmode',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('我司业务', (('直销', '直销'), ('代理', '代理'))), ('第二类:非我司业务', (('竞品', '竞品'), ('空白市场', '空白市场')))], max_length=25, null=True, verbose_name='销售模式'),
        ),
        migrations.AlterField(
            model_name='pmrresearchlist',
            name='testspermonth',
            field=models.PositiveIntegerField(default=0, help_text='注意：此处测试数为人份数，请填写该医院该项目的总体月均人份数', verbose_name='月总测试数'),
        ),
    ]
