# Generated by Django 3.2 on 2023-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0029_alter_pmrresearchlist_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmrresearchlist',
            name='saleschannel',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='销售路径和过程'),
        ),
    ]
