# Generated by Django 3.2 on 2023-05-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0030_alter_pmrresearchlist_saleschannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmrresearchlist',
            name='progress',
            field=models.TextField(blank=True, choices=[('待拜访', '待拜访'), ('初期了解中', '初期了解中'), ('有意向', '有意向'), ('申报预算', '申报预算'), ('审批中', '审批中'), ('审批通过', '审批通过'), ('待招标', '待招标'), ('招标完成', '招标完成'), ('仪器装机启用', '仪器装机启用'), ('仪器试剂均开票', '仪器试剂均开票')], help_text='仅针对23年目标新项目', max_length=255, null=True, verbose_name='进展情况'),
        ),
    ]
