# Generated by Django 3.2 on 2023-09-07 05:55

import PMRKA.models
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Marketing_Research', '0031_alter_pmrresearchlist_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器品牌')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '品牌列表',
                'db_table': 'marketing_research_v2"."Brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '公司列表',
                'db_table': 'marketing_research_v2"."Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('黄浦', '黄浦'), ('徐汇', '徐汇'), ('长宁', '长宁'), ('静安', '静安'), ('普陀', '普陀'), ('虹口', '虹口'), ('杨浦', '杨浦'), ('浦东', '浦东'), ('闵行', '闵行'), ('宝山', '宝山'), ('嘉定', '嘉定'), ('金山', '金山'), ('松江', '松江'), ('青浦', '青浦'), ('奉贤', '奉贤'), ('崇明', '崇明')], max_length=255, verbose_name='区域')),
                ('hospitalclass', models.CharField(choices=[('三级', '三级'), ('二级', '二级'), ('一级', '一级'), ('未定级', '未定级')], max_length=255, verbose_name='医院级别')),
                ('hospitalname', models.CharField(max_length=255, verbose_name='医院名称')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '医院列表',
                'db_table': 'marketing_research_v2"."Hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesmanPositionPMRKA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='岗位')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '员工职位列表',
                'db_table': 'marketing_research_v2"."SalesmanPosition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfoPMRKA',
            fields=[
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'db_table': 'django_admin_v2"."auth_user',
                'managed': False,
                'proxy': True,
            },
            bases=('Marketing_Research.userinfo',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PMRResearchListPMRKA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(blank=True, max_length=500, null=True, verbose_name='涉及品牌')),
                ('machinenumber', models.PositiveIntegerField(default=0, verbose_name='仪器数量')),
                ('testspermonth', models.PositiveIntegerField(default=0, verbose_name='月测试数')),
                ('salestotal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='年开票额')),
                ('supplier', models.TextField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('relation', models.TextField(blank=True, max_length=255, null=True, verbose_name='装机时间')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('company', models.ForeignKey(db_column='company', default=PMRKA.models.get_company_default_value, on_delete=django.db.models.deletion.CASCADE, to='PMRKA.company', verbose_name='公司')),
                ('hospital', models.ForeignKey(db_column='hospital', on_delete=django.db.models.deletion.CASCADE, to='PMRKA.hospital', verbose_name='医院')),
                ('operator', models.ForeignKey(db_column='operator', on_delete=django.db.models.deletion.CASCADE, related_name='operatorPMRKA', to='PMRKA.userinfopmrka', verbose_name='最后操作人')),
                ('salesman', models.ForeignKey(db_column='salesman', on_delete=django.db.models.deletion.CASCADE, related_name='salesmanPMRKA', to='PMRKA.userinfopmrka', verbose_name='填报人')),
            ],
            options={
                'verbose_name_plural': '市场调研列表',
                'db_table': 'marketing_research_v2"."KA_PMRResearchList',
            },
        ),
        migrations.CreateModel(
            name='PMRResearchDetailPMRKA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='科室')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品')),
                ('machinemodel', models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器型号')),
                ('machinenumber', models.PositiveIntegerField(default=1, verbose_name='仪器数量')),
                ('installdate', models.DateField(blank=True, help_text='例: 2023/09/01', null=True, verbose_name='装机日期')),
                ('expiration', models.CharField(blank=True, max_length=255, null=True, verbose_name='装机时间')),
                ('testsperday', models.PositiveIntegerField(default=0, verbose_name='日测试数')),
                ('salestotal', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='年开票额')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('relation', models.CharField(blank=True, max_length=255, null=True, verbose_name='装机时间')),
                ('adminmemo', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('brand', models.ForeignKey(db_column='brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='PMRKA.brand', verbose_name='品牌')),
                ('researchlist', models.ForeignKey(db_column='researchlist', on_delete=django.db.models.deletion.CASCADE, to='PMRKA.pmrresearchlistpmrka', verbose_name='调研列表')),
            ],
            options={
                'verbose_name_plural': '市场调研详情表',
                'db_table': 'marketing_research_v2"."KA_PMRResearchDetail',
            },
        ),
    ]
