# Generated by Django 3.2 on 2023-09-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMRKA', '0002_pmrresearchdetailpmrka_ownbusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmrresearchlistpmrka',
            name='ownmachinenumber',
            field=models.PositiveIntegerField(default=0, verbose_name='我司仪器数量'),
        ),
        migrations.AddField(
            model_name='pmrresearchlistpmrka',
            name='ownsalestotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='我司年开票额'),
        ),
        migrations.AddField(
            model_name='pmrresearchlistpmrka',
            name='owntestspermonth',
            field=models.PositiveIntegerField(default=0, verbose_name='我司月测试数'),
        ),
    ]
