# Generated by Django 3.2 on 2023-09-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMRKA', '0003_auto_20230907_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmrresearchlistpmrka',
            name='department',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='科室'),
        ),
    ]
