# Generated by Django 3.2 on 2023-09-08 06:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Research', '0031_alter_pmrresearchlist_progress'),
        ('PMRKA', '0005_pmrresearchlistpmrka_newold'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDELETE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器品牌')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '品牌列表',
                'db_table': 'marketing_research_v2"."Brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyDELETE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '公司列表',
                'db_table': 'marketing_research_v2"."Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalDELETE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('黄浦', '黄浦'), ('徐汇', '徐汇'), ('长宁', '长宁'), ('静安', '静安'), ('普陀', '普陀'), ('虹口', '虹口'), ('杨浦', '杨浦'), ('浦东', '浦东'), ('闵行', '闵行'), ('宝山', '宝山'), ('嘉定', '嘉定'), ('金山', '金山'), ('松江', '松江'), ('青浦', '青浦'), ('奉贤', '奉贤'), ('崇明', '崇明')], max_length=255, verbose_name='区域')),
                ('hospitalclass', models.CharField(choices=[('三级', '三级'), ('二级', '二级'), ('一级', '一级'), ('未定级', '未定级')], max_length=255, verbose_name='医院级别')),
                ('hospitalname', models.CharField(max_length=255, verbose_name='医院名称')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '医院列表',
                'db_table': 'marketing_research_v2"."Hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PMRResearchDetailPMRKADELETE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownbusiness', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否我司业务')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='科室')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品')),
                ('machinemodel', models.CharField(blank=True, max_length=255, null=True, verbose_name='仪器型号')),
                ('machinenumber', models.PositiveIntegerField(default=1, verbose_name='仪器数量')),
                ('installdate', models.DateField(blank=True, help_text='例: 2023/09/01', null=True, verbose_name='装机日期')),
                ('expiration', models.CharField(blank=True, max_length=255, null=True, verbose_name='装机时间')),
                ('testsperday', models.PositiveIntegerField(default=0, verbose_name='日测试数')),
                ('salestotal', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='年开票额')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('relation', models.CharField(blank=True, max_length=255, null=True, verbose_name='装机时间')),
                ('adminmemo', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '市场调研详情表',
                'db_table': 'marketing_research_v2"."KA_PMRResearchDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PMRResearchListPMRKADELETE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(blank=True, max_length=500, null=True, verbose_name='涉及品牌')),
                ('machinenumber', models.PositiveIntegerField(default=0, verbose_name='仪器数量')),
                ('ownmachinenumber', models.PositiveIntegerField(default=0, verbose_name='我司仪器数量')),
                ('testspermonth', models.PositiveIntegerField(default=0, verbose_name='月测试数')),
                ('owntestspermonth', models.PositiveIntegerField(default=0, verbose_name='我司月测试数')),
                ('salestotal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='年开票额')),
                ('ownsalestotal', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='我司年开票额')),
                ('department', models.TextField(blank=True, max_length=255, null=True, verbose_name='科室')),
                ('product', models.TextField(blank=True, max_length=255, null=True, verbose_name='产品')),
                ('supplier', models.TextField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('relation', models.TextField(blank=True, max_length=255, null=True, verbose_name='装机时间')),
                ('newold', models.CharField(blank=True, max_length=255, null=True, verbose_name='业务类型')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '市场调研列表',
                'db_table': 'marketing_research_v2"."KA_PMRResearchList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesmanPositionPMRKADELETE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='岗位')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '员工职位列表',
                'db_table': 'marketing_research_v2"."SalesmanPosition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfoPMRKADELETE',
            fields=[
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'db_table': 'django_admin_v2"."auth_user',
                'managed': False,
                'proxy': True,
            },
            bases=('Marketing_Research.userinfo',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='pmrresearchlistpmrka',
            name='product',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='pmrresearchdetailpmrka',
            name='relation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关系点'),
        ),
        migrations.AlterField(
            model_name='pmrresearchlistpmrka',
            name='relation',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='关系点'),
        ),
    ]
