# Generated by Django 3.2 on 2023-09-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMRKA', '0006_auto_20230908_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmrresearchlistpmrka',
            name='ownmachinenumberpercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='我司仪器数占比'),
        ),
        migrations.AddField(
            model_name='pmrresearchlistpmrka',
            name='ownsalestotalpercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='我司开票占比'),
        ),
        migrations.AddField(
            model_name='pmrresearchlistpmrka',
            name='owntestspermonthpercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='我司测试数占比'),
        ),
    ]
