# Generated by Django 3.2 on 2023-09-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMRKA', '0007_auto_20230908_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmrresearchlistpmrka',
            name='salestotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='年开票额'),
        ),
    ]
