# Generated by Django 3.2 on 2025-09-15 08:05

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Marketing_Research', '0031_alter_pmrresearchlist_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='品牌')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '品牌列表',
                'db_table': 'marketing_research_v2"."Brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '公司列表',
                'db_table': 'marketing_research_v2"."Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionrelation', models.CharField(blank=True, max_length=255, null=True, verbose_name='竞品关系点')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '竞品关系列表',
                'db_table': 'marketing_research_v2"."CompetitionRelation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('黄浦', '黄浦'), ('徐汇', '徐汇'), ('长宁', '长宁'), ('静安', '静安'), ('普陀', '普陀'), ('虹口', '虹口'), ('杨浦', '杨浦'), ('浦东', '浦东'), ('闵行', '闵行'), ('宝山', '宝山'), ('嘉定', '嘉定'), ('金山', '金山'), ('松江', '松江'), ('青浦', '青浦'), ('奉贤', '奉贤'), ('崇明', '崇明')], max_length=255, verbose_name='区域')),
                ('hospitalclass', models.CharField(choices=[('三级', '三级'), ('二级', '二级'), ('一级', '一级'), ('未定级', '未定级')], max_length=255, verbose_name='医院级别')),
                ('hospitalname', models.CharField(max_length=255, verbose_name='医院名称')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '医院列表',
                'db_table': 'marketing_research_v2"."Hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesmanPositionMindray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='岗位')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '员工职位列表',
                'db_table': 'marketing_research_v2"."SalesmanPosition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfoMindray',
            fields=[
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
                'db_table': 'django_admin_v2"."auth_user',
                'managed': False,
                'proxy': True,
            },
            bases=('Marketing_Research.userinfo',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='型号名称')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('brand', models.ForeignKey(blank=True, db_column='brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.brand', verbose_name='所属品牌')),
            ],
            options={
                'verbose_name_plural': '仪器型号列表',
                'db_table': 'marketing_research_v2"."MindrayInstrumentModel',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='MindrayHospitalSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mindray_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='迈瑞负责人')),
                ('director_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='主任姓名')),
                ('director_familiarity', models.CharField(blank=True, choices=[('red', '不认识'), ('yellow', '有商机在跟进'), ('green', '有明确代理商'), ('blue', '成单')], default='red', max_length=10, null=True, verbose_name='主任客情')),
                ('leader_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='组长姓名')),
                ('leader_familiarity', models.CharField(blank=True, choices=[('red', '不认识'), ('yellow', '有商机在跟进'), ('green', '有明确代理商'), ('blue', '成单')], default='red', max_length=10, null=True, verbose_name='组长客情')),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作老师姓名')),
                ('sales_mode', models.CharField(blank=True, choices=[('direct', '直销'), ('distribution', '分销'), ('notours', '非我司业务')], max_length=20, null=True, verbose_name='销售模式')),
                ('distribution_channel', models.CharField(blank=True, max_length=200, null=True, verbose_name='分销渠道')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('crp_total_volume', models.IntegerField(blank=True, default=0, verbose_name='CRP总标本量')),
                ('saa_total_volume', models.IntegerField(blank=True, default=0, verbose_name='SAA总标本量')),
                ('esr_total_volume', models.IntegerField(blank=True, default=0, verbose_name='血沉总标本量')),
                ('routine_total_volume', models.IntegerField(blank=True, default=0, verbose_name='血常规总标本量')),
                ('glycation_total_volume', models.IntegerField(blank=True, default=0, verbose_name='糖化总标本量')),
                ('urine_total_volume', models.IntegerField(blank=True, default=0, verbose_name='尿液总标本量')),
                ('blood_cell_total_count', models.IntegerField(blank=True, default=0, verbose_name='血球仪器总台数')),
                ('glycation_total_count', models.IntegerField(blank=True, default=0, verbose_name='糖化仪器总台数')),
                ('urine_total_count', models.IntegerField(blank=True, default=0, verbose_name='尿液仪器总台数')),
                ('blood_cell_summary', models.TextField(blank=True, null=True, verbose_name='血球品牌-型号-台数-装机年份-标本量')),
                ('glycation_summary', models.TextField(blank=True, null=True, verbose_name='糖化品牌-型号-台数-装机年份-标本量')),
                ('urine_summary', models.TextField(blank=True, null=True, verbose_name='尿液品牌-型号-台数-装机年份-标本量')),
                ('sales_opportunities_summary', models.TextField(blank=True, null=True, verbose_name='商机项目-型号-标本量-落地时间')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='Mindray_Research.userinfomindray', verbose_name='修改人')),
                ('director_contact', models.ForeignKey(blank=True, db_column='director_contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_contact', to='Mindray_Research.userinfomindray', verbose_name='主任对接人')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.hospital', verbose_name='医院')),
                ('leader_contact', models.ForeignKey(blank=True, db_column='leader_contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_contact', to='Mindray_Research.userinfomindray', verbose_name='组长对接人')),
                ('operator_contact', models.ForeignKey(blank=True, db_column='operator_contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_contact', to='Mindray_Research.userinfomindray', verbose_name='操作老师对接人')),
                ('qitian_manager', models.ForeignKey(db_column='qitian_manager', on_delete=django.db.models.deletion.CASCADE, related_name='qitian_manager', to='Mindray_Research.userinfomindray', verbose_name='其田负责人')),
            ],
            options={
                'verbose_name_plural': '其田市场调研列表',
                'db_table': 'marketing_research_v2"."MindrayHospitalSurvey',
            },
        ),
        migrations.CreateModel(
            name='MindrayInstrumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='仪器分类')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
            ],
            options={
                'verbose_name_plural': '仪器分类',
                'db_table': 'marketing_research_v2"."MindrayInstrumentCategory',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_project', models.CharField(choices=[('BLOOD_CELL', '血球'), ('GLYCATION', '糖化'), ('URINE', '尿液')], max_length=10, verbose_name='商机项目')),
                ('sample_volume', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='商机标本量')),
                ('landing_time', models.CharField(help_text='格式：YYYY-MM，如：2024-03', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', '格式：YYYY-MM')], verbose_name='落地时间')),
                ('opportunity_status', models.TextField(blank=True, null=True, verbose_name='商机情况')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('hospital_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.mindrayhospitalsurvey', verbose_name='医院调研')),
                ('opportunity_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mindray_Research.instrumentmodel', verbose_name='商机型号')),
                ('salesperson', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sales_opportunities', to='Mindray_Research.userinfomindray', verbose_name='销售人员')),
            ],
            options={
                'verbose_name': '销售商机',
                'verbose_name_plural': '销售商机管理',
                'db_table': 'marketing_research_v2"."MindraySalesOpportunity',
                'ordering': ['-createtime'],
            },
        ),
        migrations.CreateModel(
            name='MindrayInstrumentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_our_instrument', models.BooleanField(choices=[(True, '是'), (False, '否')], verbose_name='是否我司仪器')),
                ('our_sales_channel', models.CharField(blank=True, choices=[('direct', '直销'), ('distribution', '分销')], max_length=20, verbose_name='我司业务销售渠道')),
                ('modelmemo', models.CharField(blank=True, max_length=500, null=True, verbose_name='型号备注')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='台数')),
                ('installation_year', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', '请输入4位数字年份')], verbose_name='装机年份')),
                ('installation_location', models.CharField(blank=True, choices=[('outpatient', '门诊'), ('emergency', '急诊'), ('inpatient', '病房'), ('fever_clinic', '发热门诊'), ('physical_exam', '体检')], max_length=200, verbose_name='仪器安装地')),
                ('sample_volume', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='标本量')),
                ('dealer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='经销商名称')),
                ('blood_project_types', models.CharField(blank=True, max_length=200, null=True, verbose_name='血球项目汇总')),
                ('blood_competition_relations', models.TextField(blank=True, null=True, verbose_name='血球竞品关系点汇总')),
                ('blood_dealer_names', models.TextField(blank=True, null=True, verbose_name='血球经销商汇总')),
                ('blood_project_details', models.TextField(blank=True, null=True, verbose_name='血球项目详细汇总')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mindray_Research.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.mindrayinstrumentcategory', verbose_name='仪器分类')),
                ('competitionrelation', models.ForeignKey(blank=True, db_column='competitionrelation', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.competitionrelation', verbose_name='竞品关系点')),
                ('hospital_survey', models.ForeignKey(db_column='hospital_survey', on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.mindrayhospitalsurvey', verbose_name='医院调研')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_instrument_surveys', to='Mindray_Research.userinfomindray', verbose_name='最后修改人')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mindray_Research.instrumentmodel', verbose_name='型号')),
            ],
            options={
                'verbose_name_plural': '仪器具体信息',
                'db_table': 'marketing_research_v2"."MindrayInstrumentSurvey',
                'ordering': ['category__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunitySummary',
            fields=[
            ],
            options={
                'verbose_name': '医院商机汇总',
                'verbose_name_plural': '医院商机汇总展示',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Mindray_Research.salesopportunity',),
        ),
        migrations.CreateModel(
            name='MindrayBloodCellProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('CRP', 'CRP'), ('SAA', 'SAA'), ('ESR', '血沉'), ('CBC', '血常规')], max_length=10, verbose_name='具体项目')),
                ('sample_volume', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='标本量')),
                ('dealer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='经销商名称')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('competitionrelation', models.ForeignKey(blank=True, db_column='competitionrelation', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.competitionrelation', verbose_name='竞品关系点')),
                ('instrument_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_projects', to='Mindray_Research.mindrayinstrumentsurvey', verbose_name='仪器调研')),
            ],
            options={
                'verbose_name_plural': '血球项目详情',
                'db_table': 'marketing_research_v2"."MindrayBloodCellProject',
                'unique_together': {('instrument_survey', 'project_type')},
            },
        ),
    ]
