# Generated by Django 3.2 on 2025-09-16 02:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentmodel',
            name='brand',
            field=models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.brand', verbose_name='所属品牌'),
        ),
        migrations.AlterField(
            model_name='salesopportunity',
            name='landing_time',
            field=models.CharField(blank=True, help_text='格式：YYYY-MM，如：2024-03', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', '格式：YYYY-MM')], verbose_name='落地时间'),
        ),
        migrations.AlterField(
            model_name='salesopportunity',
            name='opportunity_project',
            field=models.CharField(blank=True, choices=[('BLOOD_CELL', '血球'), ('GLYCATION', '糖化'), ('URINE', '尿液')], max_length=10, null=True, verbose_name='商机项目'),
        ),
    ]
