# Generated by Django 3.2 on 2025-09-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindrayinstrumentsurvey',
            name='modelmemo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='型号备注'),
        ),
    ]
