# Generated by Django 3.2 on 2025-08-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindrayinstrumentsurvey',
            name='competitionrelation',
            field=models.ForeignKey(blank=True, db_column='competitionrelation', help_text='仅用于糖化和尿液类别', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.competitionrelation', verbose_name='竞品关系点'),
        ),
        migrations.AlterField(
            model_name='mindrayinstrumentsurvey',
            name='dealer_name',
            field=models.CharField(blank=True, help_text='仅用于糖化和尿液类别', max_length=200, null=True, verbose_name='经销商名称'),
        ),
        migrations.AlterField(
            model_name='mindrayinstrumentsurvey',
            name='sample_volume',
            field=models.IntegerField(blank=True, default=0, help_text='仅用于糖化和尿液类别', null=True, verbose_name='标本量'),
        ),
        migrations.CreateModel(
            name='MindrayBloodCellProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('CRP', 'CRP'), ('SAA', 'SAA'), ('ESR', '血沉'), ('CBC', '血球')], max_length=10, verbose_name='具体项目')),
                ('sample_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='标本量')),
                ('dealer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='经销商名称')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否呈现')),
                ('competitionrelation', models.ForeignKey(blank=True, db_column='competitionrelation', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.competitionrelation', verbose_name='竞品关系点')),
                ('instrument_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_projects', to='Mindray_Research.mindrayinstrumentsurvey', verbose_name='仪器调研')),
            ],
            options={
                'verbose_name_plural': '血球项目详情',
                'db_table': 'marketing_research_v2"."MindrayBloodCellProject',
                'unique_together': {('instrument_survey', 'project_type')},
            },
        ),
    ]
