# Generated by Django 3.2 on 2025-08-19 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0002_auto_20250818_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='crp_total_volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='CRP总标本量'),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='esr_total_volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='血沉总标本量'),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='routine_total_volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='血常规总标本量'),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='saa_total_volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='SAA总标本量'),
        ),
        migrations.AlterField(
            model_name='mindraybloodcellproject',
            name='project_type',
            field=models.CharField(choices=[('CRP', 'CRP'), ('SAA', 'SAA'), ('ESR', '血沉'), ('CBC', '血常规')], max_length=10, verbose_name='具体项目'),
        ),
        migrations.AlterField(
            model_name='mindrayinstrumentsurvey',
            name='competitionrelation',
            field=models.ForeignKey(blank=True, db_column='competitionrelation', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.competitionrelation', verbose_name='竞品关系点'),
        ),
        migrations.AlterField(
            model_name='mindrayinstrumentsurvey',
            name='dealer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='经销商名称'),
        ),
        migrations.AlterField(
            model_name='mindrayinstrumentsurvey',
            name='sample_volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='标本量'),
        ),
    ]
