# Generated by Django 3.2 on 2025-08-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0003_auto_20250819_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='blood_cell_summary',
            field=models.TextField(blank=True, null=True, verbose_name='血球仪器汇总'),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='blood_cell_total_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='血球仪器总台数'),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='glycation_total_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='糖化仪器总台数'),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='urine_total_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='尿液仪器总台数'),
        ),
        migrations.AlterField(
            model_name='mindrayhospitalsurvey',
            name='director_familiarity',
            field=models.CharField(blank=True, choices=[('red', '不认识'), ('yellow', '有商机在跟进'), ('green', '有明确代理商'), ('blue', '成单')], default='red', max_length=10, null=True, verbose_name='主任客情'),
        ),
        migrations.AlterField(
            model_name='mindrayhospitalsurvey',
            name='leader_familiarity',
            field=models.CharField(blank=True, choices=[('red', '不认识'), ('yellow', '有商机在跟进'), ('green', '有明确代理商'), ('blue', '成单')], default='red', max_length=10, null=True, verbose_name='组长客情'),
        ),
    ]
