# Generated by Django 3.2 on 2025-08-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0004_auto_20250819_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='glycation_summary',
            field=models.TextField(blank=True, null=True, verbose_name='糖化品牌-型号-台数-装机年份-标本量'),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='urine_summary',
            field=models.TextField(blank=True, null=True, verbose_name='尿液品牌-型号-台数-装机年份-标本量'),
        ),
        migrations.AlterField(
            model_name='mindrayhospitalsurvey',
            name='blood_cell_summary',
            field=models.TextField(blank=True, null=True, verbose_name='血球品牌-型号-台数-装机年份-标本量'),
        ),
    ]
