# Generated by Django 3.2 on 2025-08-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0005_auto_20250819_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindrayinstrumentsurvey',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_instrument_surveys', to='Mindray_Research.userinfomindray', verbose_name='最后修改人'),
        ),
    ]
