# Generated by Django 3.2 on 2025-08-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0006_mindrayinstrumentsurvey_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindrayinstrumentsurvey',
            name='blood_competition_relations',
            field=models.TextField(blank=True, null=True, verbose_name='血球竞品关系点汇总'),
        ),
        migrations.AddField(
            model_name='mindrayinstrumentsurvey',
            name='blood_dealer_names',
            field=models.TextField(blank=True, null=True, verbose_name='血球经销商汇总'),
        ),
        migrations.AddField(
            model_name='mindrayinstrumentsurvey',
            name='blood_project_types',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='血球项目汇总'),
        ),
    ]
