# Generated by Django 3.2 on 2025-08-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0007_auto_20250820_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindrayinstrumentsurvey',
            name='blood_project_details',
            field=models.TextField(blank=True, null=True, verbose_name='血球项目详细汇总'),
        ),
    ]
