# Generated by Django 3.2 on 2025-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0008_mindrayinstrumentsurvey_blood_project_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='glycation_total_volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='糖化总标本量'),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='urine_total_volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='尿液总标本量'),
        ),
    ]
