# Generated by Django 3.2 on 2025-08-25 03:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0009_auto_20250820_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_model', models.CharField(max_length=100, verbose_name='商机型号')),
                ('opportunity_project', models.CharField(choices=[('CBC', '血常规'), ('CRP', 'CRP'), ('SAA', 'SAA'), ('ESR', '血沉')], max_length=10, verbose_name='商机项目')),
                ('sample_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='商机标本量')),
                ('landing_time', models.CharField(help_text='格式：YYYY-MM，如：2024-03', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', '格式：YYYY-MM')], verbose_name='落地时间')),
                ('opportunity_status', models.TextField(blank=True, null=True, verbose_name='商机情况')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('hospital_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mindray_Research.mindrayhospitalsurvey', verbose_name='医院调研')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_opportunities', to='Mindray_Research.userinfomindray', verbose_name='销售人员')),
            ],
            options={
                'verbose_name': '销售商机',
                'verbose_name_plural': '销售商机管理',
                'db_table': 'marketing_research_v2"."SalesOpportunity',
                'ordering': ['-createtime'],
            },
        ),
    ]
