# Generated by Django 3.2 on 2025-08-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0010_salesopportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesopportunity',
            name='salesperson',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sales_opportunities', to='Mindray_Research.userinfomindray', verbose_name='销售人员'),
        ),
    ]
