# Generated by Django 3.2 on 2025-08-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0011_alter_salesopportunity_salesperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpportunitySummary',
            fields=[
            ],
            options={
                'verbose_name': '医院商机汇总',
                'verbose_name_plural': '医院商机汇总展示',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Mindray_Research.salesopportunity',),
        ),
        migrations.AddField(
            model_name='mindrayhospitalsurvey',
            name='sales_opportunities_summary',
            field=models.TextField(blank=True, null=True, verbose_name='商机汇总'),
        ),
    ]
