# Generated by Django 3.2 on 2025-08-26 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0012_auto_20250826_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindraybloodcellproject',
            name='sample_volume',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='标本量'),
        ),
        migrations.AlterField(
            model_name='mindrayinstrumentsurvey',
            name='sample_volume',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='标本量'),
        ),
        migrations.AlterField(
            model_name='salesopportunity',
            name='sample_volume',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='商机标本量'),
        ),
    ]
