# Generated by Django 3.2 on 2025-08-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0013_auto_20250826_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesopportunity',
            name='opportunity_project',
            field=models.CharField(choices=[('BLOOD_CELL', '血球'), ('GLYCATION', '糖化'), ('URINE', '尿液')], max_length=10, verbose_name='商机项目'),
        ),
    ]
