# Generated by Django 3.2 on 2025-08-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindray_Research', '0014_alter_salesopportunity_opportunity_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindrayhospitalsurvey',
            name='sales_opportunities_summary',
            field=models.TextField(blank=True, null=True, verbose_name='商机项目-型号-标本量-落地时间'),
        ),
    ]
